import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext'
import { supabase } from '../../lib/supabase'
import { accountsFromSnapshot } from '../../lib/mcpActual'
import { downloadMCPPdf } from '../../lib/mcpPdf'
import { format, parseISO } from 'date-fns'
import { Archive, FileText, Trash2, ArrowLeft } from 'lucide-react'
import { ConfirmDialog } from '../../components/ConfirmDialog'

// A permanent record of every MCP (Actual) ever generated -- each row is a
// snapshot taken at export time, so it stays accurate even if the
// underlying FCRs or accounts change later.
export const MCPArchive = () => {
  const { user } = useAuth()
  const [entries, setEntries] = useState([])
  const [loading, setLoading] = useState(true)
  const [downloadingId, setDownloadingId] = useState(null)
  const [deletingId, setDeletingId] = useState(null)
  const [error, setError] = useState('')
  const [deleteTarget, setDeleteTarget] = useState(null)

  useEffect(() => {
    fetchEntries()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user])

  const fetchEntries = async () => {
    if (!user) return
    setLoading(true)
    try {
      const { data, error } = await supabase
        .from('mcp_archive')
        .select(`*, generator:user_profiles!mcp_archive_generated_by_fkey(full_name:name)`)
        .order('month', { ascending: false })
      if (error) throw error
      setEntries(data || [])
    } catch (err) {
      // The FK-based embed above only works if that constraint name exists;
      // fall back to a plain select if it doesn't rather than showing nothing.
      const { data } = await supabase.from('mcp_archive').select('*').order('month', { ascending: false })
      setEntries(data || [])
    } finally {
      setLoading(false)
    }
  }

  const handleDownload = async (entry) => {
    setDownloadingId(entry.id)
    try {
      const snapshot = entry.snapshot || {}
      await downloadMCPPdf({
        month: snapshot.month || entry.month,
        visits: snapshot.visits || [],
        accounts: accountsFromSnapshot(snapshot),
        dailyNotes: snapshot.dailyNotes || {},
        submitterName: snapshot.submitterName,
        approverName: '',
        title: 'MONTHLY COVERAGE PLAN (ACTUAL)',
        filenamePrefix: 'MCP (Actual)',
      })
    } catch (err) {
      setError(err.message || 'Failed to regenerate this PDF')
    } finally {
      setDownloadingId(null)
    }
  }

  const handleDelete = async (id) => {
    setDeletingId(id)
    try {
      const { error } = await supabase.from('mcp_archive').delete().eq('id', id)
      if (error) throw error
      fetchEntries()
    } catch (err) {
      setError(err.message || 'Failed to delete')
    } finally {
      setDeletingId(null)
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link to="/mcp-actual" className="p-2 hover:bg-gray-100 rounded-lg transition-colors">
          <ArrowLeft size={20} />
        </Link>
        <div>
          <h1 className="text-2xl font-bold text-gray-900">MCP Archive</h1>
          <p className="text-gray-500 mt-1">Every MCP (Actual) that's been generated, saved for later reference</p>
        </div>
      </div>

      {error && (
        <div className="p-4 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700">{error}</div>
      )}

      {loading ? (
        <div className="flex items-center justify-center h-64">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600"></div>
        </div>
      ) : entries.length === 0 ? (
        <div className="card text-center py-16">
          <Archive size={48} className="mx-auto text-gray-300 mb-4" />
          <h3 className="text-lg font-medium text-gray-900">No archived MCPs yet</h3>
          <p className="text-gray-500 mt-1">Generate one from the MCP (Actual) page</p>
          <Link to="/mcp-actual" className="btn-primary mt-4 inline-flex items-center gap-2">
            Go to MCP (Actual)
          </Link>
        </div>
      ) : (
        <div className="space-y-3">
          {entries.map((entry) => (
            <div key={entry.id} className="card flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
              <div>
                <p className="font-semibold text-gray-900">
                  {format(parseISO(entry.month), 'MMMM yyyy')}
                </p>
                <p className="text-sm text-gray-500 mt-0.5">
                  {entry.fcr_count} visit{entry.fcr_count === 1 ? '' : 's'}
                  {entry.generator?.full_name ? ` · Generated by ${entry.generator.full_name}` : ''}
                  {' · '}{format(parseISO(entry.created_at), 'MMM dd, yyyy')}
                </p>
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => handleDownload(entry)}
                  disabled={downloadingId === entry.id}
                  className="btn-secondary flex items-center gap-2 text-sm disabled:opacity-50"
                >
                  <FileText size={14} /> {downloadingId === entry.id ? 'Downloading...' : 'Download PDF'}
                </button>
                {entry.generated_by === user?.id && (
                  <button
                    onClick={() => setDeleteTarget(entry.id)}
                    disabled={deletingId === entry.id}
                    className="p-2 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors disabled:opacity-50"
                  >
                    <Trash2 size={16} />
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      )}

      <ConfirmDialog
        open={deleteTarget !== null}
        onOpenChange={(isOpen) => !isOpen && setDeleteTarget(null)}
        title="Delete this archived MCP (Actual)?"
        description="This cannot be undone."
        confirmLabel="Delete"
        onConfirm={() => handleDelete(deleteTarget)}
      />
    </div>
  )
}
